In [1]:
import pandas as pd
df = pd.read_csv('lab 4-5\\ThiTHPT2018.csv')
df1 = df.copy()

C:\Users\thebao\AppData\Local\Temp\ipykernel_2108\3378964178.py:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('lab 4-5\\ThiTHPT2018.csv')

In [3]:
#thay thế trường toán bằng giá trị trung bình
TBToan = df1['Toan'].mean()
print(TBToan)
df1['Toan'].fillna(TBToan, inplace = True)
#df1['Toan']

4.884687182628491

In [5]:
#thay thế giá trị thiếu trường văn bằng giá trị thường xuyên
print(df1['Van'].mode())
df1['Van'].fillna(df1['Van'].mode())

0    6.0
Name: Van, dtype: float64

0         3.75
1         7.50
2         5.50
3         5.75
4         6.75
          ...
744391    4.50
744392    6.00
744393    3.50
744394    4.50
744395    3.50
Name: Van, Length: 744396, dtype: float64

In [3]:
#thay giá trị thiếu cho trường anh văn
#giatritxcuatinh = df1.groupby('Ten Tinh')['Anh'].apply(lambda x: x.mode())
df1['Anh'] = df1['Anh'].fillna(df1.groupby('Ten Tinh')['Anh'].apply(lambda x: x.mean()))
#df.groupby('Ten Tinh')['Anh'].fillna(....)
#print(giatritxcuatinh)
df1['Anh']

0         3.0
1         9.0
2         4.0
3         2.6
4         3.0
         ...
744391    6.0
744392    5.0
744393    4.0
744394    5.4
744395    3.0
Name: Anh, Length: 744396, dtype: float64

In [10]:
#thay giá trị không thi
df1.fillna(value={'Ly': 'khongthi', 'Hoa': 'khongthi', 'Sinh': 'khongthi',
                  'Su': 'khongthi', 'Dia': 'khongthi','GDCD': 'khongthi',
                  'KhoiA': 'khongthi', 'KhoiB': 'khongthi', 'KhoiC': 'khongthi',
                  'KhoiD': 'khongthi', 'KhoiA1': 'khongthi'}, inplace=True)

In [12]:
#kiemtratyle[kiemtratyle > 0.5]
kiemtratyle = df1.isnull().mean()
#xóa những cột có giá trị thiếu trên 50%
df1.drop(kiemtratyle[kiemtratyle > 0.5].index[1:len(df1.columns)-3], axis=1)

,SoBD,Toan,Van,Anh,Ly,Su,Dia,GDCD,KhoiC,KhoiD,Ma Tinh,Ten Tinh,Vung mien
0,1,3.0,3.75,3.0,NaN,3.0,6.50,8.25,13.25,9.75,18,Bac Giang,Mien Bac
1,2,8.8,7.50,9.0,NaN,6.0,9.00,8.25,22.50,25.3,18,Bac Giang,Mien Bac
2,3,6.0,5.50,4.0,5.75,NaN,NaN,NaN,NaN,15.5,18,Bac Giang,Mien Bac
3,4,3.4,5.75,2.6,NaN,3.5,4.75,7.25,14.00,11.75,18,Bac Giang,Mien Bac
4,5,3.8,6.75,3.0,NaN,3.5,6.25,8.00,16.50,13.55,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,4.6,4.50,6.0,3.75,NaN,NaN,NaN,NaN,15.1,52,Ba Ria Vung Tau,Mien Nam
744392,744393,7.0,6.00,5.0,5.25,NaN,NaN,NaN,NaN,18,52,Ba Ria Vung Tau,Mien Nam
744393,744394,5.2,3.50,4.0,6.25,NaN,NaN,NaN,NaN,12.7,52,Ba Ria Vung Tau,Mien Nam
744394,744395,7.8,4.50,5.4,7.50,NaN,NaN,NaN,NaN,17.7,52,Ba Ria Vung Tau,Mien Nam
744395,744396,5.8,3.50,3.0,6.25,NaN,NaN,NaN,NaN,12.3,52,Ba Ria Vung Tau,Mien Nam

In [94]:
#điền giá trị 0 cho những ô bị thiếu
df1[4:].fillna(0)

,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,Dia,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
4,5,3.8,6.75,3.0,khongthi,khongthi,khongthi,3.5,6.25,8.0,0.0,khongthi,khongthi,16.5,13.55,khongthi,18,Bac Giang,Mien Bac
5,6,5.0,6.50,2.2,2.0,3.5,4.25,khongthi,khongthi,khongthi,0.0,10.5,12.75,khongthi,13.7,9.2,18,Bac Giang,Mien Bac
6,7,2.4,6.25,3.6,khongthi,khongthi,khongthi,5.0,6.0,8.0,0.0,khongthi,khongthi,17.25,12.25,khongthi,18,Bac Giang,Mien Bac
7,8,2.6,3.75,3.0,khongthi,khongthi,khongthi,3.0,4.5,7.75,0.0,khongthi,khongthi,11.25,9.35,khongthi,18,Bac Giang,Mien Bac
8,9,4.8,7.25,2.2,4.0,5.0,4.25,khongthi,khongthi,khongthi,0.0,13.8,14.05,khongthi,14.25,11.0,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,4.6,4.50,6.0,3.75,3.0,3.25,khongthi,khongthi,khongthi,0.0,11.35,10.85,khongthi,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,7.0,6.00,5.0,5.25,5.5,4.0,khongthi,khongthi,khongthi,0.0,17.75,16.5,khongthi,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,5.2,3.50,4.0,6.25,5.5,2.25,khongthi,khongthi,khongthi,0.0,16.95,12.95,khongthi,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,7.8,4.50,5.4,7.5,6.25,3.0,khongthi,khongthi,khongthi,0.0,21.55,17.05,khongthi,17.7,20.7,52,Ba Ria Vung Tau,Mien Nam
744395,744396,5.8,3.50,3.0,6.25,4.75,3.25,khongthi,khongthi,khongthi,0.0,16.8,13.8,khongthi,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [95]:
#điền giá trị NaN cho những ô thiếu
df1[4:].fillna('NaN')

,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,Dia,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
4,5,3.8,6.75,3.0,khongthi,khongthi,khongthi,3.5,6.25,8.0,NaN,khongthi,khongthi,16.5,13.55,khongthi,18,Bac Giang,Mien Bac
5,6,5.0,6.5,2.2,2.0,3.5,4.25,khongthi,khongthi,khongthi,NaN,10.5,12.75,khongthi,13.7,9.2,18,Bac Giang,Mien Bac
6,7,2.4,6.25,3.6,khongthi,khongthi,khongthi,5.0,6.0,8.0,NaN,khongthi,khongthi,17.25,12.25,khongthi,18,Bac Giang,Mien Bac
7,8,2.6,3.75,3.0,khongthi,khongthi,khongthi,3.0,4.5,7.75,NaN,khongthi,khongthi,11.25,9.35,khongthi,18,Bac Giang,Mien Bac
8,9,4.8,7.25,2.2,4.0,5.0,4.25,khongthi,khongthi,khongthi,NaN,13.8,14.05,khongthi,14.25,11.0,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,4.6,4.5,6.0,3.75,3.0,3.25,khongthi,khongthi,khongthi,NaN,11.35,10.85,khongthi,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,7.0,6.0,5.0,5.25,5.5,4.0,khongthi,khongthi,khongthi,NaN,17.75,16.5,khongthi,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,5.2,3.5,4.0,6.25,5.5,2.25,khongthi,khongthi,khongthi,NaN,16.95,12.95,khongthi,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,7.8,4.5,5.4,7.5,6.25,3.0,khongthi,khongthi,khongthi,NaN,21.55,17.05,khongthi,17.7,20.7,52,Ba Ria Vung Tau,Mien Nam
744395,744396,5.8,3.5,3.0,6.25,4.75,3.25,khongthi,khongthi,khongthi,NaN,16.8,13.8,khongthi,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [16]:
#<20%
dulieuthieu = df1.isnull().mean()
#print(dulieuthieu)
# Xác định các cột có tỷ lệ giá trị thiếu dưới 20%
timcot = dulieuthieu[dulieuthieu < 0.2].index
#print(timcot)
for col in timcot:
    if df1[col].dtype == 'object':
        df1[col].fillna(df1[col].mode()[0], inplace=True)
    else:
        df1[col].fillna(df1[col].mean(), inplace=True)

Index(['SoBD', 'Toan', 'Van', 'Anh', 'KhoiD', 'Ma Tinh', 'Ten Tinh',
       'Vung mien'],
      dtype='object')

In [98]:
#chuẩn hóa
from scipy.stats import zscore
df1.dropna()
df1_data_Hoa = df['Hoa']
df1_data_Ly = df['Ly']
df1_data_Dia = df['Dia']

z_score_hoa=zscore(df1_data_Hoa)
z_score_Ly=zscore(df1_data_Ly)
z_score_Ly=zscore(df1_data_Dia)

z_score_hoa

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
744391   NaN
744392   NaN
744393   NaN
744394   NaN
744395   NaN
Name: Hoa, Length: 744396, dtype: float64

In [99]:
df1.to_csv('TotnghiepOK.csv')