In [51]:
import pandas as pd
df = pd.read_csv('lab 4-5//105.csv')
df

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh,...,Toan roi rac,Tri tue nhan tao,Triet hoc 1,Triet hoc 2,TT Ho Chi Minh,VL Dai cuong 1,VL Dai cuong 2,Visual Basic,Xac suat,Unnamed: 55
0,9.0,9.0,7.0,9.0,8.0,10.0,NaN,9.0,7.0,10.0,...,8.0,9.0,8.0,7.0,NaN,9.0,7.0,10.0,8.0,NaN
1,6.0,8.0,6.0,7.0,8.0,5.0,NaN,8.0,5.0,7.0,...,6.0,8.0,6.0,6.0,NaN,9.0,7.0,5.0,5.0,NaN
2,7.0,8.0,7.0,5.0,7.0,5.0,NaN,7.0,7.0,10.0,...,8.0,5.0,8.0,6.0,NaN,8.0,8.0,10.0,5.0,NaN
3,5.0,6.0,5.0,7.0,3.0,5.0,NaN,5.0,5.0,7.0,...,6.0,5.0,6.0,5.0,NaN,3.0,5.0,6.0,5.0,NaN
4,5.0,8.0,5.0,7.0,6.0,6.0,NaN,6.0,6.0,5.0,...,5.0,5.0,8.0,5.0,NaN,6.0,7.0,6.0,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,NaN,6.0,6.0,7.0,6.0,8.0,6.0,8.0,7.0,5.0,...,6.0,8.0,5.0,6.0,6.0,7.0,6.0,5.0,5.0,5.0
95,NaN,5.0,7.0,6.0,8.0,7.0,7.0,7.0,7.0,5.0,...,9.0,5.0,5.0,7.0,5.0,6.0,6.0,5.0,9.0,7.0
96,NaN,7.0,7.0,8.0,8.0,9.0,8.0,8.0,8.0,9.0,...,9.0,9.0,8.0,8.0,8.0,9.0,9.0,9.0,10.0,7.0
97,NaN,7.0,5.0,5.0,6.0,9.0,6.0,6.0,8.0,6.0,...,7.0,5.0,6.0,6.0,5.0,7.0,5.0,7.0,6.0,9.0
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0

In [52]:
cols = df.columns.tolist()
for col in cols:
    #print(df[col])
    df[col] = df[col].apply(lambda x: 1 if x >= 6 else 0)

df

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh,...,Toan roi rac,Tri tue nhan tao,Triet hoc 1,Triet hoc 2,TT Ho Chi Minh,VL Dai cuong 1,VL Dai cuong 2,Visual Basic,Xac suat,Unnamed: 55
0,1,1,1,1,1,1,0,1,1,1,...,1,1,1,1,0,1,1,1,1,0
1,1,1,1,1,1,0,0,1,0,1,...,1,1,1,1,0,1,1,0,0,0
2,1,1,1,0,1,0,0,1,1,1,...,1,0,1,1,0,1,1,1,0,0
3,0,1,0,1,0,0,0,0,0,1,...,1,0,1,0,0,0,0,1,0,0
4,0,1,0,1,1,1,0,1,1,0,...,0,0,1,0,0,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0,1,1,1,1,1,1,1,1,0,...,1,1,0,1,1,1,1,0,0,0
95,0,0,1,1,1,1,1,1,1,0,...,1,0,0,1,0,1,1,0,1,1
96,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
97,0,1,0,0,1,1,1,1,1,1,...,1,0,1,1,0,1,0,1,1,1
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [54]:
df_moi = df.copy()
df_moi.to_csv('105moi.csv')