In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [28]:
df = pd.read_csv('Market_Basket_AR.csv')
df

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
from mlxtend.frequent_patterns import fpgrowth

In [29]:
items = (df['shrimp'].unique())
items

array(['burgers', 'chutney', 'turkey', 'mineral water', 'low fat yogurt',
       'whole wheat pasta', 'soup', 'frozen vegetables', 'french fries',
       'eggs', 'cookies', 'spaghetti', 'shrimp', 'meatballs', 'red wine',
       'rice', 'parmesan cheese', 'ground beef', 'sparkling water',
       'herb & pepper', 'pickles', 'energy bar', 'fresh tuna', 'escalope',
       'avocado', 'tomato sauce', 'clothes accessories', 'energy drink',
       'chocolate', 'grated cheese', 'yogurt cake', 'mint', 'asparagus',
       'champagne', 'ham', 'muffins', 'french wine', 'chicken', 'pasta',
       'tomatoes', 'pancakes', 'frozen smoothie', 'carrots', 'yams',
       'shallot', 'butter', 'light mayo', 'pepper', 'candy bars',
       'cooking oil', 'milk', 'green tea', 'bug spray', 'oil',
       'olive oil', 'salmon', 'cake', 'almonds', 'salt', 'strong cheese',
       'hot dogs', 'pet food', 'whole wheat rice', 'antioxydant juice',
       'honey', 'sandwich', 'salad', 'magazines', 'protein bar',
       'mayonnaise', 'cider', 'burger sauce', 'green grapes',
       'vegetables mix', 'bramble', 'nonfat milk', 'tomato juice',
       'green beans', 'strawberries', 'eggplant', 'mushroom cream sauce',
       'gums', 'cereals', 'flax seed', 'spinach', 'soda', 'dessert wine',
       'corn', 'fresh bread', 'brownies', 'fromage blanc',
       'chocolate bread', 'mashed potato', 'gluten free bar',
       'cottage cheese', 'whole weat flour', 'chili', 'barbecue sauce',
       'light cream', 'mint green tea', 'black tea', 'bacon', 'shampoo',
       'blueberries', 'cauliflower', 'extra dark chocolate', 'white wine',
       'babies food', 'toothpaste', 'melons', 'ketchup', 'cream',
       'hand protein bar', 'body spray', 'oatmeal'], dtype=object)

In [30]:
encoded_vals = []
for index, row in df.iterrows():
    labels = {}
    uncommons = list(set(items) - set(row))
    commons = list(set(items).intersection(row))
    for uc in uncommons:
        labels[uc] = 0
    for com in commons:
        labels[com] = 1
    encoded_vals.append(labels)
encoded_vals[0]
ohe_df = pd.DataFrame(encoded_vals)

In [32]:
freq_items = fpgrowth(ohe_df.astype('bool'), min_support=0.02, use_colnames=True)
freq_items.head()

    support     itemsets
0  0.179733       (eggs)
1  0.087200    (burgers)
2  0.020933  (meatballs)
3  0.062533     (turkey)
4  0.033200    (avocado)

In [33]:
rules = association_rules(freq_items, metric="confidence", min_threshold=0.1)
rules.head(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(mineral water),(eggs),0.238267,0.179733,0.050933,0.213766,1.189351,0.008109,1.043286
1,(eggs),(mineral water),0.179733,0.238267,0.050933,0.283383,1.189351,0.008109,1.062957
2,(burgers),(eggs),0.087200,0.179733,0.028800,0.330275,1.837585,0.013127,1.224782
3,(eggs),(burgers),0.179733,0.087200,0.028800,0.160237,1.837585,0.013127,1.086974
4,(mineral water),(burgers),0.238267,0.087200,0.024400,0.102406,1.174384,0.003623,1.016941