In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [3]:
df = pd.read_csv('105OK.csv')
df

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh,...,Toan roi rac,Tri tue nhan tao,Triet hoc 1,Triet hoc 2,TT Ho Chi Minh,VL Dai cuong 1,VL Dai cuong 2,Visual Basic,Xac suat,Unnamed: 55
0,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
1,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
2,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
3,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
4,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
95,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
96,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
97,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
98,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [7]:
df_10 = df.iloc[:, :10]
df_10

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh
0,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,False,True,True,True
2,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,False,True,True,True
4,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...
94,False,True,True,True,True,True,True,True,True,True
95,False,True,True,True,True,True,True,True,True,True
96,False,True,True,True,True,True,True,True,True,True
97,False,True,True,True,True,True,True,True,True,True
98,False,False,False,False,False,False,False,False,False,False

In [9]:
frequent_itemsets_40 = apriori(df_10, min_support=0.4, use_colnames=True)
frequent_itemsets_40

      support                                           itemsets
0    0.525253                                           (Access)
1    0.989899                                       (CT du lieu)
2    0.989899                                      (CT may tinh)
3    0.989899                                           (CNXHKH)
4    0.989899                                       (Chuyen de )
..        ...                                                ...
762  0.464646  (CS du lieu, CT may tinh, Chuyen de , CNphan m...
763  0.464646  (CS du lieu, CNXHKH, Chuyen de , CNphan mem, C...
764  0.464646  (CS du lieu, CT may tinh, CNXHKH, Chuyen de , ...
765  0.525253  (CS du lieu, CT may tinh, CNXHKH, Chuyen de , ...
766  0.464646  (CS du lieu, CT may tinh, CNXHKH, Chuyen de , ...

[767 rows x 2 columns]

In [10]:
from mlxtend.frequent_patterns import association_rules
rules=association_rules(frequent_itemsets_40, metric="confidence", min_threshold=0.6)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Access),(CT du lieu),0.525253,0.989899,0.525253,1.0,1.010204,0.005306,inf
1,(Access),(CT may tinh),0.525253,0.989899,0.525253,1.0,1.010204,0.005306,inf
2,(Access),(CNXHKH),0.525253,0.989899,0.525253,1.0,1.010204,0.005306,inf
3,(Access),(Chuyen de ),0.525253,0.989899,0.525253,1.0,1.010204,0.005306,inf
4,(Access),(CS du lieu),0.525253,0.989899,0.525253,1.0,1.010204,0.005306,inf
...,...,...,...,...,...,...,...,...,...
18655,"(CNphan mem, Cong nghe NET )","(CS du lieu, CT may tinh, CNXHKH, Chuyen de , ...",0.464646,0.989899,0.464646,1.0,1.010204,0.004693,inf
18656,"(CT du lieu, Cong nghe NET )","(CS du lieu, CT may tinh, CNXHKH, CNphan mem, ...",0.464646,0.989899,0.464646,1.0,1.010204,0.004693,inf
18657,"(Dai so so hoc, Cong nghe NET )","(CS du lieu, CT may tinh, CNXHKH, CNphan mem, ...",0.464646,0.989899,0.464646,1.0,1.010204,0.004693,inf
18658,"(DS tuyen tinh, Cong nghe NET )","(CS du lieu, CT may tinh, CNXHKH, CNphan mem, ...",0.464646,0.989899,0.464646,1.0,1.010204,0.004693,inf
18659,(Cong nghe NET ),"(CS du lieu, CT may tinh, CNXHKH, Chuyen de , ...",0.464646,0.989899,0.464646,1.0,1.010204,0.004693,inf